In [2]:
import numpy as np

## Lists and Arrays

In [3]:
list1 = [10, 20, 30]
list1

[10, 20, 30]

In [4]:
arr1 = np.array(list1)
arr1

array([10, 20, 30])

In [6]:
arr2 = np.arange(10, 20, 1)  # (start, stop, step size)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

## 3-dimensional array

In [10]:
arr3dim = np.array([[[1, 2, 3], [3, 4, 5]], [[5, 6, 7], [7, 8, 9]]])
arr3dim

array([[[1, 2, 3],
        [3, 4, 5]],

       [[5, 6, 7],
        [7, 8, 9]]])

In [12]:
arr3dim * 3

array([[[ 3,  6,  9],
        [ 9, 12, 15]],

       [[15, 18, 21],
        [21, 24, 27]]])

In [24]:
arr3dim[1]

array([[5, 6, 7],
       [7, 8, 9]])

In [36]:
for x in np.nditer(arr3dim):  # n-dimensional iteration
    print(x, end=", ")

1, 2, 3, 3, 4, 5, 5, 6, 7, 7, 8, 9, 

## Array sum, stdv, var, max

In [19]:
arr4 = arr1 * arr1
arr4

array([100, 400, 900])

In [21]:
arr4.sum()

1400

In [33]:
print("Standard deviation: ", arr4.std())
print("Variance: ", arr4.var())
print("Maximum: ", arr4.max())

Standard deviation:  329.98316455372213
Variance:  108888.88888888888
Maximum:  900


In [31]:
for x in arr1:
    print(x)

10
20
30
